export {
  createDiagnostic,
  DiagnosticSeverity,
  type Diagnostic,
} from "./diagnostics.js";
export {
  INTERACTION_LIMITS_VERSION,
  INTERACTION_WHITESPACE_CLASSIFICATION,
  MAX_INTERACTION_AGGREGATE_UTF8_BYTES,
  MAX_INTERACTION_OPTION_ENTRIES,
  MAX_INTERACTION_STRING_UTF8_BYTES,
  interactionUtf8ByteLength,
} from "./interaction-limits.js";
export { lex, type LexResult } from "./lexer.js";
export { parse, type ParseResult } from "./parser.js";
export {
  CORE_RUNTIME_BUILTINS,
  compileSource,
  type CompilationResult,
  type CompileOptions,
} from "./compiler.js";
export {
  INSTRUCTION_PLAN_FORMAT,
  INSTRUCTION_PLAN_VERSION,
  type ArgumentPlan,
  type AssignmentTargetPlan,
  type ExpressionPlan,
  type Instruction,
  type WaitInstruction,
  type InteractionInstruction,
  type PrepareInteractionSpeakerInstruction,
  type InteractionKind,
  type InteractionResultDomain,
  type InteractionUiPayload,
  type InteractionChoiceOption,
  type InteractionAccessibleName,
  type PreparedInteractionUiPayload,
  type PreparedInteractionChoiceLabel,
  type InstructionPlan,
  type PlanSourceLocation,
  type LoopControlInstruction,
  type LoopStartInstruction,
  type RangeExpressionPlan,
  type CompiledFunctionDefinition,
  type CompiledFunctionParameter,
  type CallFunctionInstruction,
  type CallArgumentPlan,
  type TemporaryExpressionPlan,
} from "./plan/model.js";
export {
  validateInstructionPlan,
  type PlanValidationError,
  type PlanValidationResult,
} from "./plan/validation.js";
export {
  validateSemantics,
  type SemanticValidationOptions,
  type SemanticValidationResult,
} from "./semantic.js";
export type { RuntimeErrorInfo } from "./runtime/errors.js";
export type { RuntimeWarningInfo } from "./runtime/warnings.js";
export type {
  ActionCompletedEvent,
  ActionRequestedEvent,
  PlayerTranscriptEvent,
  ExitEvent,
  CompleteEvent,
  DeveloperWarningEvent,
  InterpreterEvent,
  OutputSpeaker,
  RuntimeFailureEvent,
  SayEvent,
} from "./runtime/events.js";
export {
  executeInstruction,
  run,
  RuntimeDataError,
  stepToEvent,
  type RuntimeBuiltinFunction,
  type RuntimeCapabilities,
  type RuntimeCapabilityCall,
  type RuntimeOperationResult,
  type RuntimeRunOptions,
} from "./runtime/engine.js";
export { completeAction } from "./runtime/operations/complete-action.js";
export { observeTime } from "./runtime/operations/observe-time.js";
export type {
  PendingActionOperationResult,
  TimeObservationOutcome,
  ActionCompletionOutcome,
} from "./runtime/operations/model.js";
export {
  CHECKPOINT_FORMAT,
  CHECKPOINT_VERSION,
  CheckpointError,
  createCheckpoint,
  deserializeCheckpoint,
  restoreCheckpoint,
  serializeCheckpoint,
  type CheckpointErrorInfo,
  type RuntimeCheckpoint,
} from "./runtime/checkpoint.js";
export {
  createFreshRuntimeSnapshot,
  DEFAULT_MAX_CALL_DEPTH,
  MAX_RUNTIME_SESSION_TIME_MS,
  MAX_SUPPORTED_CALL_DEPTH,
  RUNTIME_SNAPSHOT_FORMAT,
  RUNTIME_SNAPSHOT_VERSION,
  validateRuntimeSnapshot,
  type FreshRuntimeOptions,
  type RuntimeBindingSnapshot,
  type RuntimeFailureSnapshot,
  type RuntimeScopeFrameSnapshot,
  type RuntimeLoopFrameSnapshot,
  type RuntimeCallArgumentSnapshot,
  type RuntimeCallFrameSnapshot,
  type RuntimeParameterStateSnapshot,
  type RuntimeTemporarySnapshot,
  type RuntimeRepeatLoopFrameSnapshot,
  type RuntimeForLoopFrameSnapshot,
  type RuntimeWhileLoopFrameSnapshot,
  type RuntimeSnapshot,
  type RuntimeSpeakerSnapshot,
  type RuntimeStatus,
  type SnapshotValidationResult,
} from "./runtime/state.js";
export type {
  RuntimeActionSettlementSnapshot,
  RuntimeDelayActionSnapshot,
  RuntimeInteractionActionSnapshot,
  RuntimeDelayActionSettlementSnapshot,
  RuntimeInteractionActionSettlementSnapshot,
  RuntimePendingActionSnapshot,
} from "./runtime/actions/model.js";
export {
  DEFAULT_PLAYGROUND_SEED,
  createXorShift32State,
  nextXorShift32,
  XORSHIFT32_ALGORITHM,
  type XorShift32State,
} from "./runtime/random.js";
export {
  cloneSerializableValue,
  createSerializableList,
  createSerializableObject,
  createSerializableSet,
  type SerializableRuntimeList,
  type SerializableRuntimeObject,
  type SerializableRuntimeRange,
  type SerializableRuntimeProperty,
  type SerializableRuntimeScalar,
  type SerializableRuntimeSet,
  type SerializableRuntimeValue,
  type SerializableSpeakerReference,
} from "./runtime/serializable-values.js";
export {
  combineSourceSpans,
  createSourcePosition,
  createSourceSpan,
  type SourcePosition,
  type SourceSpan,
} from "./source.js";
export { createToken, TokenKind, type Token } from "./token.js";
export type {
  AssignmentStatement,
  AssignmentTarget,
  BinaryExpression,
  BreakStatement,
  Block,
  BooleanLiteral,
  CallArgument,
  CallExpression,
  ContinueStatement,
  ExitStatement,
  Expression,
  ExpressionStatement,
  ForStatement,
  FunctionDeclaration,
  FunctionParameter,
  Identifier,
  IfStatement,
  IndexExpression,
  InterpolationExpression,
  InteractionExpression,
  LetStatement,
  ListLiteral,
  NamedArgument,
  NullLiteral,
  NumberLiteral,
  ObjectLiteral,
  ObjectProperty,
  ParenthesizedExpression,
  PositionalArgument,
  Program,
  PropertyAccessExpression,
  RangeExpression,
  RepeatStatement,
  ReturnStatement,
  ScalarTypeName,
  SayStatement,
  ShowButtonStatement,
  WaitStatement,
  SetLiteral,
  SpeakerDeclaration,
  SpeakerProperty,
  SpeakerSetterStatement,
  Statement,
  StringExpression,
  StringLiteral,
  TemplateInterpolation,
  TemplateLiteral,
  TemplatePart,
  TemplateText,
  TypeAnnotation,
  UnaryExpression,
  WhileStatement,
} from "./ast.js";
