export { createDiagnostic, DiagnosticSeverity, type Diagnostic } from "./diagnostics.js";
export {
  cloneMessageMarkup,
  escapeMarkup,
  isMessageMarkup,
  messageMarkupVisibleText,
  parseMessageMarkup,
  type MessageMarkup,
  type MessageMarkupBlock,
  type MessageMarkupHeading,
  type MessageMarkupLine,
  type MessageMarkupLineEnding,
  type MessageMarkupList,
  type MessageMarkupListItem,
  type MessageMarkupParagraph,
  type MessageMarkupQuote,
  type MessageMarkupSpan,
} from "./message-markup.js";
export {
  INTERACTION_LIMITS_VERSION,
  INTERACTION_WHITESPACE_CLASSIFICATION,
  MAX_INTERACTION_AGGREGATE_UTF8_BYTES,
  MAX_INTERACTION_OPTION_ENTRIES,
  MAX_INTERACTION_STRING_UTF8_BYTES,
  interactionUtf8ByteLength,
} from "./interaction-limits.js";
export { lex, type LexResult } from "./lexer.js";
export { parse, type ParseResult } from "./parser.js";
export type { ScriptHeader } from "./script-header.js";
export { normalizeTagName, type Tag } from "./tags.js";
export {
  readImageXmpKeywords,
  readXmpPacketKeywords,
  type XmpKeywordsResult,
} from "./xmp-keywords.js";
export {
  CORE_RUNTIME_BUILTINS,
  PLATFORM_STANDARD_LIBRARY_PRELUDE,
  compileProject,
  compileSource,
  type CompilationResult,
  type CompileOptions,
  type ProjectCompilationResult,
  type ProjectDiagnostic,
  type ProjectFileCompilation,
  type ProjectSourceFile,
} from "./compiler.js";
export type { ProjectImageFile } from "./image-catalog.js";
export { MAIN_FILE_PATH } from "./project-paths.js";
export {
  INSTRUCTION_PLAN_FORMAT,
  INSTRUCTION_PLAN_VERSION,
  type ArgumentPlan,
  type AssignmentTargetPlan,
  type ExpressionPlan,
  type Instruction,
  type WaitInstruction,
  type InteractionInstruction,
  type PrepareInteractionSpeakerInstruction,
  type InteractionKind,
  type InteractionResultDomain,
  type InteractionUiPayload,
  type InteractionChoiceOption,
  type InteractionAccessibleName,
  type PreparedInteractionUiPayload,
  type PreparedInteractionChoiceValue,
  type InstructionPlan,
  type PlanFile,
  type PlanSourceLocation,
  type LoopControlInstruction,
  type LoopStartInstruction,
  type RangeExpressionPlan,
  type CompiledFunctionDefinition,
  type CompiledFunctionParameter,
  type CallFunctionInstruction,
  type CallArgumentPlan,
  type TemporaryExpressionPlan,
} from "./plan/model.js";
export {
  validateInstructionPlan,
  type PlanValidationError,
  type PlanValidationResult,
} from "./plan/validation.js";
export {
  validateSemantics,
  type SemanticValidationOptions,
  type SemanticValidationResult,
} from "./semantic.js";
export type { RuntimeErrorInfo } from "./runtime/errors.js";
export type { RuntimeWarningInfo } from "./runtime/warnings.js";
export {
  applyLanguageTextEdits,
  createLanguageDocument,
  formatLanguageDocument,
  languageCompletions,
  languageContextHelp,
  languageDiagnostics,
  languageHover,
  languagePositionAt,
  languageProjectOverview,
  languageSignatureHelp,
  type LanguageCompletionItem,
  type LanguageContextHelp,
  type LanguageDiagnostic,
  type LanguageDocument,
  type LanguageFileOverview,
  type LanguageFormatResult,
  type LanguageHover,
  type LanguagePosition,
  type LanguageProjectFile,
  type LanguageRange,
  type LanguageSignatureHelp,
  type LanguageTextEdit,
} from "./language-tooling.js";
export {
  inspectRuntimeState,
  type InvalidRuntimeStateInspection,
  type RuntimeActionInspection,
  type RuntimeInspectionError,
  type RuntimeInspectionResult,
  type RuntimePreparedSayInspection,
  type RuntimeSettlementInspection,
  type RuntimeStateInspection,
} from "./runtime/inspection.js";
export type {
  ActionCompletedEvent,
  ActionRequestedEvent,
  PlayerTranscriptEvent,
  ExitEvent,
  DeveloperWarningEvent,
  InterpreterEvent,
  OutputSpeaker,
  PermanentButtonPressedEvent,
  RuntimeFailureEvent,
  SayEvent,
  ScriptStorageEditedEvent,
} from "./runtime/events.js";
export {
  validateScriptStorageEntries,
  type RuntimeScriptStorageEntrySnapshot,
} from "./runtime/script-storage.js";
export {
  executeInstruction,
  run,
  RuntimeDataError,
  stepToEvent,
  type RuntimeBuiltinFunction,
  type RuntimeCapabilities,
  type RuntimeCapabilityCall,
  type RuntimeOperationResult,
  type RuntimeRunOptions,
} from "./runtime/engine.js";
export {
  completeAction,
  type ActionCompletionOptions,
} from "./runtime/operations/complete-action.js";
export type { CapturedMediaAdmission } from "./runtime/actions/capture.js";
export { observeTime, type MediaProgressReport } from "./runtime/operations/observe-time.js";
export {
  RUNTIME_DEBUG_TRACE_LIMITS,
  RuntimeDebugContext,
  type RuntimeDebugDependency,
  type RuntimeDebugLocation,
  type RuntimeDebugRandomOperation,
  type RuntimeDebugRecord,
  type RuntimeDebugRecordDetail,
  type RuntimeDebugRecordKind,
  type RuntimeDebugTraceOptions,
  type RuntimeDebugTraceOrigin,
  type RuntimeDebugTraceStatus,
  type RuntimeDebugUnrecordedReason,
} from "./runtime/debug-trace.js";
export {
  recordContinueCapture,
  type ContinueCaptureOutcome,
} from "./runtime/operations/continue-capture.js";
export {
  applyExternalStorageEdit,
  type ExternalStorageEditOutcome,
} from "./runtime/operations/external-storage-edit.js";
export type { RuntimeTemporalCapture } from "./runtime/temporal-captures.js";
export {
  reportMediaLoad,
  type MediaLoadReport,
  type MediaReportOutcome,
} from "./runtime/operations/media-reports.js";
export {
  pressPermanentButton,
  type PermanentButtonPressOutcome,
} from "./runtime/operations/press-permanent-button.js";
export {
  permanentButtonProjection,
  type PermanentButtonProjection,
  type RuntimePermanentButtonSnapshot,
} from "./runtime/permanent-buttons.js";
export {
  mediaPlaybackProjection,
  stageProjection,
  type MediaPlaybackProjection,
  type StageProjection,
} from "./runtime/media-projection.js";
export type {
  PendingActionOperationResult,
  TimeObservationOutcome,
  ActionCompletionOutcome,
} from "./runtime/operations/model.js";
export {
  CHECKPOINT_FORMAT,
  CHECKPOINT_VERSION,
  CheckpointError,
  createCheckpoint,
  deserializeCheckpoint,
  restoreCheckpoint,
  serializeCheckpoint,
  type CheckpointErrorInfo,
  type RuntimeCheckpoint,
} from "./runtime/checkpoint.js";
export {
  createFreshRuntimeSnapshot,
  DEFAULT_MAX_CALL_DEPTH,
  MAX_RUNTIME_SESSION_TIME_MS,
  MAX_SUPPORTED_CALL_DEPTH,
  RUNTIME_SNAPSHOT_FORMAT,
  RUNTIME_SNAPSHOT_VERSION,
  validateRuntimeSnapshot,
  type FreshRuntimeOptions,
  type RuntimeBindingSnapshot,
  type RuntimeFailureSnapshot,
  type RuntimeScopeFrameSnapshot,
  type RuntimeLoopFrameSnapshot,
  type RuntimeCallArgumentSnapshot,
  type RuntimeCallFrameSnapshot,
  type RuntimeFileCallFrameSnapshot,
  type RuntimeFrameSnapshot,
  type RuntimeParameterStateSnapshot,
  type RuntimeTemporarySnapshot,
  type RuntimeRepeatLoopFrameSnapshot,
  type RuntimeForLoopFrameSnapshot,
  type RuntimeWhileLoopFrameSnapshot,
  type RuntimeSnapshot,
  type RuntimeSpeakerSnapshot,
  type RuntimeStatus,
  type SnapshotValidationResult,
} from "./runtime/state.js";
export type {
  CaptureUnavailableReason,
  RuntimeActionSettlementSnapshot,
  RuntimeCaptureActionSettlementSnapshot,
  RuntimeCaptureActionSnapshot,
  RuntimeDelayActionSnapshot,
  RuntimeInteractionActionSnapshot,
  RuntimeMediaActionSnapshot,
  RuntimeMediaPlaybackActionSnapshot,
  RuntimeMediaPlaybackSettlementSnapshot,
  RuntimeMediaSettlementSnapshot,
  RuntimeDelayActionSettlementSnapshot,
  RuntimeInteractionActionSettlementSnapshot,
  RuntimePendingActionSnapshot,
  RuntimePreparedSayOutputSnapshot,
  RuntimeStorageWriteActionSnapshot,
  RuntimeStorageWriteSettlementSnapshot,
} from "./runtime/actions/model.js";
export { interactionDeadlineMs } from "./runtime/actions/model.js";
export {
  DEFAULT_PLAYGROUND_SEED,
  createXorShift32State,
  nextXorShift32,
  XORSHIFT32_ALGORITHM,
  type XorShift32State,
} from "./runtime/random.js";
export {
  cloneSerializableValue,
  createSerializableList,
  createSerializableObject,
  createSerializableSet,
  type SerializableRuntimeList,
  type SerializableRuntimeObject,
  type SerializableRuntimeRange,
  type SerializableRuntimeProperty,
  type SerializableRuntimeScalar,
  type SerializableRuntimeSet,
  type SerializableRuntimeDict,
  type SerializableRuntimeDictEntry,
  type SerializableRuntimeValue,
  type SerializableSpeakerReference,
  type SerializableMediaHandle,
  type SerializableScriptReference,
  type SerializableRuntimeDate,
  type SerializableRuntimeDateTime,
  type SerializableRuntimeTime,
  type SerializableRuntimeTimestamp,
} from "./runtime/serializable-values.js";
export {
  DEFAULT_TEMPORAL_CONTEXT,
  type PresentationSettings,
  type TemporalContext,
  type ZoneRules,
} from "./temporal.js";
export { captureTemporalContext } from "./temporal-capture.js";
export {
  combineSourceSpans,
  createSourcePosition,
  createSourceSpan,
  type SourcePosition,
  type SourceSpan,
} from "./source.js";
export { createToken, TokenKind, type Token } from "./token.js";
export type {
  AssignmentStatement,
  AssignmentTarget,
  BinaryExpression,
  BreakStatement,
  Block,
  BooleanLiteral,
  CallArgument,
  CallExpression,
  ContinueStatement,
  ExitStatement,
  Expression,
  ExpressionStatement,
  ForStatement,
  FunctionDeclaration,
  FunctionParameter,
  Identifier,
  IfStatement,
  IndexExpression,
  InterpolationExpression,
  InteractionExpression,
  LetStatement,
  ListLiteral,
  NamedArgument,
  NullLiteral,
  NumberLiteral,
  ObjectLiteral,
  ObjectProperty,
  ParenthesizedExpression,
  PositionalArgument,
  Program,
  PropertyAccessExpression,
  RangeExpression,
  RepeatStatement,
  ReturnStatement,
  ScalarTypeName,
  SayStatement,
  ShowButtonStatement,
  SwitchCase,
  SwitchStatement,
  SwitchTypeTest,
  WaitStatement,
  TimerStatement,
  ShowImageStatement,
  HideImageStatement,
  MediaCue,
  MediaHandlers,
  MediaKind,
  MediaParts,
  MediaRepeat,
  PlayMediaExpression,
  PlayMediaStatement,
  SetLiteral,
  DictEntry,
  DictLiteral,
  SpeakerDeclaration,
  SpeakerProperty,
  SpeakerSetterStatement,
  Statement,
  StringExpression,
  StringInterpolation,
  StringLiteral,
  StringPart,
  StringText,
  TypeAnnotation,
  TypeName,
  NamedType,
  CollectionType,
  OptionalType,
  UnionType,
  UnaryExpression,
  WhileStatement,
} from "./ast.js";
export type { MessagePresentation } from "./message-presentation.js";
