/** Names reserved by the accepted V30 TeaseScript specification. */
export const TEASESCRIPT_GRAMMAR_KEYWORDS = Object.freeze([
  "let",
  "function",
  "return",
  "if",
  "else",
  "switch",
  "case",
  "default",
  "repeat",
  "for",
  "in",
  "while",
  "break",
  "continue",
  "and",
  "or",
  "not",
  "true",
  "false",
  "null",
  "choose",
  "speaker",
  "say",
  "as",
  "label",
  "goto",
  "run",
  "call",
  "end",
  "exit",
  "save",
  "load",
  "delete",
] as const);

export const TEASESCRIPT_PROTECTED_TYPE_NAMES = Object.freeze([
  "string",
  "boolean",
  "integer",
  "number",
  "date",
  "time",
  "datetime",
  "duration",
] as const);

export const TEASESCRIPT_PROTECTED_ENGINE_NAMES = Object.freeze([
  "player",
  "random",
  "randomInteger",
  "chance",
  "toString",
  "toNumber",
  "toInteger",
  "toBoolean",
  "toDate",
  "toTime",
  "toDateTime",
  "getDate",
  "getTime",
  "getDateTime",
  "getSeconds",
  "getMilliseconds",
  "schedule",
  "cancelSchedule",
  "askText",
  "askNumber",
  "askInteger",
  "askBoolean",
  "askDate",
  "askTime",
  "askDateTime",
  "wait",
  "timer",
  "mysteryTimer",
  "startTimer",
  "stopTimer",
  "showPermanentButton",
  "removePermanentButton",
  "playSound",
  "playVideo",
  "playBackgroundSound",
  "stopBackgroundSound",
  "showBackgroundColor",
  "showBackgroundImage",
  "showBackgroundVideo",
  "showOverlayImage",
  "showOverlayVideo",
  "showImage",
  "moveOverlay",
  "animateOverlay",
  "hideOverlay",
  "hideImage",
  "showBlur",
  "hideBlur",
  "drawRectangle",
  "drawEllipse",
  "drawLine",
  "drawText",
  "removeDrawing",
  "account",
  "askAccountChange",
  "publishGlobal",
  "getGlobal",
  "loadFromScript",
  "getScriptMetadata",
  "getPlayerHistory",
] as const);

export const CORE_RUNTIME_BUILTINS = Object.freeze([
  "random",
  "chance",
  "randomInteger",
] as const);

export const TEASESCRIPT_PROTECTED_NAMES = Object.freeze([
  ...TEASESCRIPT_GRAMMAR_KEYWORDS,
  ...TEASESCRIPT_PROTECTED_TYPE_NAMES,
  ...TEASESCRIPT_PROTECTED_ENGINE_NAMES,
] as const);
