/** Names reserved by the accepted V30 TeaseScript specification. */
const TEASESCRIPT_GRAMMAR_KEYWORDS = Object.freeze([
  "let",
  "function",
  "return",
  "if",
  "else",
  "switch",
  "case",
  "default",
  "repeat",
  "for",
  "in",
  "while",
  "break",
  "continue",
  "and",
  "or",
  "not",
  "set",
  "true",
  "false",
  "null",
  "choose",
  "speaker",
  "say",
  "as",
  "label",
  "goto",
  "call",
  "end",
  "exit",
  "fallback",
  "global",
  "tagged",
  "save",
  "load",
  "delete",
  "is",
] as const);

const TEASESCRIPT_PROTECTED_TYPE_NAMES = Object.freeze([
  "string",
  "boolean",
  "integer",
  "number",
  "date",
  "time",
  "datetime",
  "absoluteDateTime",
  "calendarDuration",
  // The earlier name stays reserved, so its use is a compile error that names the fix (ADR 0026).
  "timestamp",
  "duration",
  "list",
  "dict",
  "object",
  "range",
  "media",
  "messageHandle",
  "script",
] as const);

const TEASESCRIPT_PROTECTED_ENGINE_NAMES = Object.freeze([
  "player",
  "random",
  "randomInteger",
  "chance",
  "round",
  "floor",
  "ceil",
  "min",
  "max",
  "abs",
  "sqrt",
  "pow",
  "sign",
  "mod",
  "clamp",
  "pi",
  "debugMode",
  "sum",
  "average",
  "median",
  "percentile",
  "stddev",
  "linearRegression",
  "predict",
  "randomWeighted",
  "exp",
  "ln",
  "log10",
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  "randomNormal",
  "randomBeta",
  "randomPert",
  "toString",
  "toNumber",
  "toInteger",
  "toBoolean",
  "toDate",
  "toTime",
  "toDateTime",
  "toAbsoluteDateTime",
  "getDate",
  "getTime",
  "getDateTime",
  "getAbsoluteDateTime",
  // The earlier names stay reserved, so their calls are compile errors that name the fix (ADR 0026).
  "toTimestamp",
  "getTimestamp",
  "schedule",
  "cancelSchedule",
  "askText",
  "askNumber",
  "showButton",
  "takePhoto",
  "askImage",
  "askInteger",
  "askBoolean",
  "askBooleans",
  "askForm",
  "askDate",
  "askTime",
  "askDateTime",
  "wait",
  "timer",
  "showPermanentButton",
  "removePermanentButton",
  "playAudio",
  "playVideo",
  "stopAudio",
  "showBackgroundColor",
  "showBackgroundImage",
  "showOverlayImage",
  "showOverlayVideo",
  "showImage",
  "moveOverlay",
  "animateOverlay",
  "hideOverlay",
  "hideImage",
  "showCamera",
  "hideCamera",
  "showBlur",
  "hideBlur",
  "drawRectangle",
  "drawEllipse",
  "drawLine",
  "drawText",
  "removeDrawing",
  "account",
  "askAccountChange",
  "publishGlobal",
  "getGlobal",
  "loadFromScript",
  "getScriptMetadata",
  "getPlayerHistory",
  "findImages",
  "findScripts",
] as const);

export const CORE_RUNTIME_BUILTINS = Object.freeze([
  "random",
  "chance",
  "randomInteger",
  "toString",
  "toNumber",
  "toInteger",
  "toBoolean",
  "round",
  "floor",
  "ceil",
  "min",
  "max",
  "abs",
  "sqrt",
  "pow",
  "sign",
  "mod",
  "clamp",
  "sum",
  "average",
  "median",
  "percentile",
  "stddev",
  "linearRegression",
  "predict",
  "randomWeighted",
  "exp",
  "ln",
  "log10",
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  "randomNormal",
  "randomBeta",
  "randomPert",
  "toDate",
  "toTime",
  "toDateTime",
  "toAbsoluteDateTime",
  "getDate",
  "getTime",
  "getDateTime",
  "getAbsoluteDateTime",
  "script",
  "removePermanentButton",
] as const);

/** The earlier names of core built-ins, whose calls are compile errors that name the fix (ADR 0026). */
export const RENAMED_BUILTINS: ReadonlyMap<string, string> = new Map([
  ["getTimestamp", "getAbsoluteDateTime"],
  ["toTimestamp", "toAbsoluteDateTime"],
]);

/** The earlier names of methods, whose calls are compile errors that name the fix on any value (ADR 0026). */
export const RENAMED_METHODS: ReadonlyMap<string, string> = new Map([
  ["toTimestamp", "toAbsoluteDateTime"],
]);

/** Temporary direct-call bridge for implemented Platform Standard Library helpers. */
export const PLATFORM_STANDARD_LIBRARY_PRELUDE = Object.freeze(["escapeMarkup"] as const);

export const TEASESCRIPT_PROTECTED_NAMES = Object.freeze([
  ...TEASESCRIPT_GRAMMAR_KEYWORDS,
  ...TEASESCRIPT_PROTECTED_TYPE_NAMES,
  ...TEASESCRIPT_PROTECTED_ENGINE_NAMES,
  ...PLATFORM_STANDARD_LIBRARY_PRELUDE,
] as const);
